export const SET_BILLING_GROUP = 'SET_BILLING_GROUP';
export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_COMPANY_SEARCH_STRING = 'SET_COMPANY_SEARCH_STRING';
export const SET_JOB_NUMBERS = 'SET_JOB_NUMBERS';
export const SET_PATIENT_ID_VALUE = 'SET_PATIENT_ID_VALUE';
export const SET_PURCHASE_ORDER = 'SET_PURCHASE_ORDER';
export const SET_SEARCHED_JOB_NUMBER_STRING = 'SET_SEARCHED_JOB_NUMBER_STRING';
