export const SET_PATIENT_ID_VALUE = 'SET_PATIENT_ID_VALUE';
export const SET_COMPANY_SEARCH_STRING = 'SET_COMPANY_SEARCH_STRING';
export const SET_SEARCHED_JOB_NUMBER_STRING = 'SET_SEARCHED_JOB_NUMBER_STRING';
export const SET_JOB_NUMBERS = 'SET_JOB_NUMBERS';
